DROP TABLE IF EXISTS gas_status;
DROP TABLE IF EXISTS fire_status;
DROP TABLE IF EXISTS temp_status;
DROP TABLE IF EXISTS boards;
DROP TABLE IF EXISTS rooms;
DROP TABLE IF EXISTS homes;
DROP TABLE IF EXISTS users;
