PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS users (
  u_id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  email TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS homes (
  h_id INTEGER PRIMARY KEY AUTOINCREMENT,
  u_id INTEGER NOT NULL,
  h_name TEXT NOT NULL,
  CONSTRAINT homes_user_fk FOREIGN KEY (u_id) REFERENCES users(u_id)
);

CREATE TABLE IF NOT EXISTS rooms (
  r_id INTEGER PRIMARY KEY AUTOINCREMENT,
  r_name TEXT,
  h_id INTEGER NOT NULL,
  CONSTRAINT rooms_home_fk FOREIGN KEY (h_id) REFERENCES homes(h_id)
);

CREATE TABLE IF NOT EXISTS boards (
  b_id INTEGER PRIMARY KEY AUTOINCREMENT,
  b_name TEXT NOT NULL,
  u_id INTEGER NOT NULL,
  r_id INTEGER,
  status INTEGER DEFAULT 0,
  CONSTRAINT boards_user_fk FOREIGN KEY (u_id) REFERENCES users(u_id),
  CONSTRAINT boards_room_fk FOREIGN KEY (r_id) REFERENCES rooms(r_id)
);

CREATE TABLE IF NOT EXISTS temp_status (
  b_id INTEGER NOT NULL,
  temp NUMERIC DEFAULT NULL,
  humi NUMERIC DEFAULT NULL,
  CONSTRAINT temp_status_board_fk FOREIGN KEY (b_id) REFERENCES boards(b_id)
);

CREATE TABLE IF NOT EXISTS fire_status (
  b_id INTEGER NOT NULL,
  fire_lv NUMERIC NOT NULL DEFAULT 0,
  status INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT fire_status_board_fk FOREIGN KEY (b_id) REFERENCES boards(b_id)
);

CREATE TABLE IF NOT EXISTS gas_status (
  b_id INTEGER NOT NULL,
  co_2 NUMERIC DEFAULT NULL,
  ch_4 NUMERIC DEFAULT NULL,
  lpg NUMERIC DEFAULT NULL,
  CONSTRAINT gas_status_board_fk FOREIGN KEY (b_id) REFERENCES boards(b_id)
);
